/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ilkka' at '12/15/17 10:02 PM' with Gradle 2.8
 *
 * @author ilkka, @date 12/15/17 10:02 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
